import "../styles/Mypage.scss";

export default function Mypage() {
  return (
    <>
      <hr />
      <table>
        <tr id="header">
          <th>No.</th>
          <th>성함</th>
          <th>날짜</th>
          <th>제목</th>
          <th>button</th>
        </tr>
        <tr>
          <td>John</td>
          <td>Doe</td>
          <td>24</td>
          <td>KOREA</td>
          <td>
            <button>삭제</button>
          </td>
        </tr>
        <tr>
          <td>John</td>
          <td>Doe</td>
          <td>24</td>
          <td>KOREA</td>
          <td>
            <button>삭제</button>
          </td>
        </tr>
        <tr>
          <td>John</td>
          <td>Doe</td>
          <td>24</td>
          <td>KOREA</td>
          <td>
            <button>삭제</button>
          </td>
        </tr>
        <tr>
          <td>John</td>
          <td>Doe</td>
          <td>24</td>
          <td>KOREA</td>
          <td>
            <button>삭제</button>
          </td>
        </tr>
        <tr>
          <td>John</td>
          <td>Doe</td>
          <td>24</td>
          <td>KOREA</td>
          <td>
            <button>삭제</button>
          </td>
        </tr>
        <tr>
          <td>John</td>
          <td>Doe</td>
          <td>24</td>
          <td>KOREA</td>
          <td>
            <button>삭제</button>
          </td>
        </tr>
        <tr>
          <td>John</td>
          <td>Doe</td>
          <td>24</td>
          <td>KOREA</td>
          <td>
            <button>삭제</button>
          </td>
        </tr>
      </table>
    </>
  );
}
